version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: redlock-web-2.0
    ports:
      - "7077:80"
    volumes:
      - ./websites:/var/www/html

  mysql_db:
    image: mysql:latest
    container_name: db-RedlockWeb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dbRedlockWeb.sql:/docker-entrypoint-initdb.d/dbRedlockWeb.sql